name: Build and deploy Blazor app to Azure Web App - conquest-of-lords
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: '.' # Modify this to your project path if not in root

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies and Build'
        shell: pwsh
        run: |
          pushd './${{ env.PROJECT_PATH }}'
          dotnet publish --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D4994106EBB4699B0CEF7C1776613E2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A0DAB0D289A4093B53685E7C6070C5C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9188986FDA594EADAC6565F4C0A8F7A6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'conquest-of-lords'
          slot-name: 'Production'
          package: '${{ env.PROJECT_PATH }}/output'
